name: CI with yarn

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: |
          npm install yarn --global

      - name: Install npx
        run: |
          yarn global add npx

      - name: Install dependencies
        run: |
          yarn

      - name: Run Build
        run: |
          yarn build
